### ISSUE TITLE
CharacterRM的训练方法

### ISSUE THREAD

**Issue by xuguohai** [morecry/CharacterEval#10]
请问CharacterRM训练方法是什么？

猜想：基于人工标注的five-point scale数据，构造排序数据，以pair-wise loss训练的reward的模型吗？

<img width="500" alt="image" src="https://github.com/morecry/CharacterEval/assets/111968302/83532a3e-9140-49a0-97b0-2bbe9b6e1a8e">

**Comment by morecry** [comment]
你好，感谢关注我们的工作。正如文中说的，我们标注是根据5级制进行打分的而不是pair-wise的，所以没有对比信息来做pair-wise loss，因此我们考虑了两种point-wise的方式，一种是当作分类问题来预测5个类别，另一种是当作回归问题来拟合绝对数值，经我们测试发现后者测试出来的和人工标注的一致性更强，所以我们最终采用的是回归loss来训练我们的CharacterRM，并用于之后的评测。

**Comment by xuguohai** [comment]
thx.
